# .github/workflows/ci-cd.yml
name: Docker Backend CI/CD

on:
  push:
    branches: [main]
    paths:
      - "backend/**"
      - ".github/workflows/ci-cd.yml"
  pull_request:
    branches: [main]
    paths:
      - "backend/**"
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image (dry run)
        run: |
          docker build --no-cache ./backend --file ./backend/Dockerfile
          # Verify tf_model.h5 size (should be ~220 MB)
          docker run --rm $(docker build -q ./backend --file ./backend/Dockerfile) \
            bash -c "ls -lh bias_classification_model/tf_model.h5"
        continue-on-error: true  # Optional: For debugging

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bias-classifier:latest